### ISSUE TITLE
Match exact vs include json

### ISSUE THREAD

**Issue by DamirSvrtan** [WhitePayments/match_json#7]
Hey there,

Is there a reason why this only watches if a part of json is included, not match it exactly?

When I add new data in my responses I would expect that it will fail, not just get swallowed (because the gems check if all the expected are in the actual, not also if all in the actual are in the expected).

Thnx, love the work!

**Comment by alovak** [comment]
Do be honest I don't remember why this gems does not include exact match...

@DamirSvrtan you can use json-schema https://github.com/ruby-json-schema/json-schema to validate whole json (what is required, what is optional).

so here is an example of matcher for json-schema:

```ruby
RSpec::Matchers.define :match_response_schema do |schema, options = {}|
  match do |response|
    schema_directory = "#{Dir.pwd}/spec/fixtures/api"
    schema_path = "#{schema_directory}/#{schema}.json"

    json_string = response.is_a?(String) ? response : response.body

    JSON::Validator.validate!(schema_path, json_string, options)
  end
end
```

and here is schema example:

```json
{
  "type": "object",
  "properties": {
    "email": {
      "type": "string",
      "format": "email"
    },
    "object": {
      "type": "string",
      "enum": [
        "user"
      ]
    },
    "id": {
      "type": "string"
    },
    "country_name": {
      "type": "string"
    },
    "created_at": {
      "type": "string",
      "format": "date-time"
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    }
  },

  "required": ["country_name"]
}
```

in your specs you can test json like this:

```ruby
expect(response).to match_response_schema(:user)
```

Also, json-schema has a lot of options so it worth learning it :)

**Comment by DamirSvrtan** [comment]
@alovak I've been using json-schema but I'm not satisfied with the amount of writing I have to do, and that's why I've turned to match_json.

Is this actively used and supported, or have you guys totally turned to json-schema?

**Comment by alovak** [comment]
We use it all the time, but as for now it satisfies us completely :)

we are open for any updates/PRs :)

**Comment by DamirSvrtan** [comment]
Do you use it in parallel with json schema? If yes, doesn't it feel a bit redundant to use both?

**Comment by alovak** [comment]
Yes, we use it in parallel. match_json is used when we need to check some specific parts of json. we rarely check whole json. but in order to be sure that whole json is valid we test it against schema.

**Comment by DamirSvrtan** [comment]
Thnx for the explanation, closing this!
